rename_me_errors_list:  
test igrf.py: small change in output files.  someone else must debug.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 647, in complete_igrf_test
    raise Exception('small change in output files.  someone else must debug')

test tdt_magic.py: TDT_magic pull up gui window and can not be tested.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1271, in complete_TDT_magic_test
    raise Exception('TDT_magic pull up gui window and can not be tested')

test lnp_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 927, in complete_lnp_magic_test
    lnp_magic.run_program()
  File "Rename_me.py", line 79, in run_program
    obj = env.run(self.name, '-WD', directory, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test HUJI_magic.py: initializing variables were removed.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1281, in complete_HUJI_magic_test
    raise NameError('initializing variables were removed')

programs with errors: ['test igrf.py', 'test tdt_magic.py', 'test lnp_magic.py', 'test HUJI_magic.py']

